name: vynt
description: "Vynt is a dynamic social media application centered around music, 
              allowing users to share their favorite tracks, discover new artists, 
              and connect with fellow music enthusiasts. Built with Flutter, Vynt 
              provides a seamless and engaging experience for music lovers."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  #/---[Icons]---/
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1
  flutter_svg: ^2.0.14

  #/---[Fonts]---/
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0

  #/---[UI]---/
  crystal_navigation_bar: ^1.0.1
  flutter_card_swiper: ^7.0.2
  cupertino_onboarding: ^1.2.0
  modal_bottom_sheet: ^3.0.0
  shared_preferences: ^2.3.3
  pull_down_button: ^0.10.2
  modular_ui: ^0.0.5 # TODO: Implements the buttons in this package
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  share_plus: ^10.1.2

  #/---[State Management]---/
  provider: ^6.1.2
  page_transition: ^2.1.0

  #/---[Splash Screen]---/
  flutter_native_splash: ^2.4.3
  animated_splash_screen: ^1.3.0

  #/---[Animations]---/
  marquee: ^2.3.0
  animate_do: ^3.3.4

  #/---[Firebase]---/
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  flutter_secure_storage: ^9.2.2

  #/---[Networking]---/
  flutter_dotenv: ^5.2.1
  uuid: ^4.5.1
  http: ^1.2.2
  url_launcher: ^6.3.1
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  oauth2_client: ^3.3.0

  #/---[Utilities]---/
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/icon_facebook.png
    - assets/icons/icon_google.svg
    - assets/icons/icon_apple.svg
    - assets/icons/logo/vynt_logo.png
    - assets/icons/logo/splash_screen_vynt_logo.png
    - assets/arts/cover_art.png
    - assets/arts/vinyl_status.png
    - assets/arts/vinyl_art.png
    - assets/test_pictures/daniele_pfp.png
    - assets/test_pictures/iava_pfp.png
    - assets/test_pictures/michele_pfp.jpeg
    - assets/test_pictures/test_post.webp
    - assets/test_pictures/cover_art/1.jpeg
    - assets/test_pictures/cover_art/2.jpeg
    - assets/test_pictures/cover_art/3.jpeg
    - assets/test_pictures/cover_art/4.jpeg
    - assets/test_pictures/cover_art/5.jpeg
    - assets/test_pictures/cover_art/6.jpeg
    - assets/test_pictures/cover_art/7.jpeg
    - assets/test_pictures/cover_art/8.jpeg
    - assets/test_pictures/cover_art/9.jpeg
    - assets/test_pictures/cover_art/10.jpeg
    - assets/test_pictures/icons/spotify.webp
    - assets/test_pictures/icons/apple_music.png


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
