// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_KEY'] ?? '',
    appId: '1:91243704533:web:6b2ab2d394125c9c1a325c',
    messagingSenderId: '91243704533',
    projectId: 'vynt-iava',
    authDomain: 'vynt-iava.firebaseapp.com',
    storageBucket: 'vynt-iava.appspot.com',
    measurementId: 'G-QS36XYH31P',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_KEY'] ?? '',
    appId: '1:91243704533:android:93d4a24fc325c7f01a325c',
    messagingSenderId: '91243704533',
    projectId: 'vynt-iava',
    storageBucket: 'vynt-iava.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_KEY'] ?? '',
    appId: '1:91243704533:ios:df2730c95e67540a1a325c',
    messagingSenderId: '91243704533',
    projectId: 'vynt-iava',
    storageBucket: 'vynt-iava.appspot.com',
    iosBundleId: 'com.vynt.app.vynt',
  );
}
