name: Flutter Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [android, ios]
    runs-on: ${{ matrix.platform == 'android' && 'ubuntu-latest' || 'macos-latest' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java (for Android)
        if: matrix.platform == 'android'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Android APK
        if: matrix.platform == 'android'
        run: flutter build apk --release

      - name: Build iOS
        if: matrix.platform == 'ios'
        run: flutter build ios --no-codesign

      # TODO: Fix the build iOS step adding the ipa file to the artifacts

      - name: Upload APK
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk